site_name: vano-next | HTB Notes
site_url: https://vano-next.github.io/HTB-notes/
repo_url: https://github.com/vano-next/HTB-notes
repo_name: vano-next/HTB-notes

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate

nav:
  - Home: index.md
    - Active Directory Enumeration & Attacks:
      - Introduction: active-directory/intro.md
  - Pivoting, Tunneling & Port Forwarding:
    - The Networking Behind Pivoting: pivoting/networking-behind-pivoting.md
    - Dynamic Port Forwarding SSH & SOCKS: pivoting/dynamic-port-forwarding.md
    - Remote/Reverse Port Forwarding: pivoting/remote-reverse-port-forwarding.md
    - Meterpreter Tunneling: pivoting/meterpreter-tunneling.md
    - Socat Reverse Shell: pivoting/socat-reverse-shell.md
    - Socat Bind Shell: pivoting/socat-bind-shell.md
    - Web Server Pivoting with Rpivot: pivoting/rpivot.md
    - Port Forwarding with Netsh: pivoting/netsh-port-forwarding.md
    - DNS Tunneling with Dnscat2: pivoting/dns-tunneling-dnscat2.md
    - SOCKS5 Tunneling with Chisel: pivoting/chisel-socks5.md
    - ICMP Tunneling with ptunnel-ng: pivoting/icmp-tunneling-ptunnel.md
    - SocksOverRDP: pivoting/socksoverrdp.md
    - Skills Assessment: pivoting/skills-assessment.md
